In [ ]:
import numpy as np
import pandas as pd
import nltk
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
import re
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
messages = pd.read_csv('/content/SMSSpamCollection', sep='\t',
                           names=["label", "message"])

In [ ]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
wnl = WordNetLemmatizer()
calci = []

In [ ]:
for i in range(0,len(messages)):
  msg = re.sub('[^a-zAZ]',' ',messages['message'][i])
  msg = msg.lower()
  msg = msg.split()
  msg = [wnl.lemmatize(i) for i in msg if not i in set(stopwords.words("english"))]
  msg = ' '.join(msg)
  calci.append(msg)


In [ ]:
calci

['jurong point crazy available bugis n great world la e buffet ine got amore wat',
 'k lar oking wif u oni',
 'ree entry wkly comp win final tkts st ay ext receive entry question std txt rate apply',
 'dun say early hor c already say',
 'ah think go usf life around though',
 'ree sg ey darling week word back like fun still b ok x std chgs send rcv',
 'ven brother like speak hey treat like aid patent',
 'per request elle elle ru innaminunginte urungu ettam set callertune allers res copy friend allertune',
 'valued network customer selected receivea prize reward claim call laim code alid hour',
 'ad mobile month entitled pdate latest colour mobile camera ree obile pdate',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'chance win rom pound txt send ost p day day sand apply eply info',
 'ou week membership rize ackpot xt word www dbuk net',
 'searching right word thank breather promise wont take help granted fulfil promise ou wonderful blessing time',
 '',
 'obi

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
x = tf.fit_transform(calci).toarray()

In [ ]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
y = pd.get_dummies(messages['label'])
y

ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [ ]:
y = y.iloc[:,1].values

In [ ]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.20, random_state = 0)

In [ ]:
print(x_train.shape)

(4457, 7279)


In [ ]:
print(y_train.shape)

(4457,)


In [ ]:
print(x_test.shape)

(1115, 7279)


In [ ]:
print(y_test.shape)

(1115,)


In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
y_pred = nb.predict(x_test)

In [ ]:
print(y_test)

[0 1 0 ... 0 1 0]


In [ ]:
print(y_pred)

[0 0 0 ... 0 1 0]


In [ ]:
from sklearn.metrics import confusion_matrix
cf = confusion_matrix(y_test,y_pred)
cf

array([[955,   0],
       [ 36, 124]])

In [ ]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test,y_pred)
ac

0.967713004484305